version: 2
jobs:
  build:
    docker:
    - image: docker:18.09-git
    steps:
    - run:
       name: 'setup git-lfs'
       command: |
         apk add git-lfs
         git lfs install
    - checkout
    - setup_remote_docker
    - run:
        name: 'Build the pdf'
        command: |
          apk add --no-cache make
          docker create -v /workdir --name code alpine:3.4 /bin/true
          echo "sending repository"
          docker cp ./. code:/workdir
          echo "building"
          make slides DOCKER_OPTIONS="--volumes-from code --name build"
          echo "retrieving artifacts"
          docker cp build:/workdir/slides/introduction.pdf .
          ls -al
    - persist_to_workspace:
        root: .
        paths:
          - introduction.pdf

  release:
    docker:
    # ubuntu doesn't package 'hub' cli
    - image: archlinux/base
    steps:
    - run:
        name: 'install tools for release'
        command: |
          pacman -Sy --noconfirm --noprogressbar git hub openssh tar

    - checkout
    - attach_workspace:
        at: build
    - run:
        name: 'release'
        command: |
          hub release create -a build/introduction.pdf \
          -m "${CIRCLE_TAG}" "${CIRCLE_TAG}"


workflows:
  version: 2
  build_and_release:
    jobs:
    - build:
        filters:
          tags:
            only: /^v.*/
    - release:
        context: kube-training-release
        requires:
        - build
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore: /.*/
