apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    prometheus: kube-prometheus
  name: kube-prometheus-exporter-coredns
  namespace: kube-ops
spec:
  endpoints:
  - bearerTokenFile: |-
      var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 15s
    port: http-metrics-coredns
  jobLabel: component
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      app: exporter-coredns
      component: coredns
