name: build-pdf
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout github repo'
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: 'Checkout LFS objects'
        run: git lfs checkout
      - name: 'Build pdf'
        run: docker-compose run build
      - name: Upload pdf as artifact
        uses: actions/upload-artifact@v2
        with:
          name: introduction.pdf
          path: slides/introduction.pdf
